version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: smart_edu_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - laravel_storage:/var/www/storage
      - laravel_cache:/var/www/bootstrap/cache
    depends_on:
      - postgres

  nginx:
    image: nginx:stable
    container_name: smart_edu_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
       - laravel_storage:/var/www/storage
      - laravel_cache:/var/www/bootstrap/cache
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:16
    container_name: smart_edu_postgres
    environment:
      POSTGRES_DB: smart_edu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: smart_edu_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartedu.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
  laravel_storage:
  laravel_cache: